[package]
name = "ipasir-sys"
version = "0.3.0"
authors = ["Chris Patuzzo <chris@patuzzo.co.uk>"]
edition = "2018"
license = "MIT"
readme = "README.md"
repository = "https://github.com/tuzz/ipasir-sys"
documentation = "https://github.com/tuzz/ipasir-sys"
homepage = "https://crates.io/crates/ipasir-sys"
description = "A Rust crate that contains FFI bindings for IPASIR-compatible SAT solvers."
keywords = ["ipasir", "ffi", "incremental", "sat", "satisfiability"]
categories = ["external-ffi-bindings", "science"]
travis-ci = "tuzz/ipasir-sys"
exclude = ["vendor/cadical/src/makefile"]

[build-dependencies]
bindgen = "0.51.0"
copy_dir = "0.1.2"
